In [48]:
import numpy as np
import pandas as pd

In [49]:
a = np.array(([13,35,74,48], [23,37,37,38], [73,39,93,39]))
print(a)

a[0:3, 1:3]

[[13 35 74 48]
 [23 37 37 38]
 [73 39 93 39]]


array([[35, 74],
       [37, 37],
       [39, 93]])

##### test font

another comment

In [50]:
a = np.array([0,1,2,3,4,5])
a[0:3] = 5
print(a)

[5 5 5 3 4 5]


In [51]:
a=np.arange(0,10)
print(a)
a < 3

[0 1 2 3 4 5 6 7 8 9]


array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [52]:
f = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])
f['daisy']

np.int64(5)

In [53]:
data = {'col_B': [1, 2, 3], 'col_A': [4, 5, 6], 'col_C': [7, 8, 9]}
df = pd.DataFrame(data)

df.sort_values(by='col_C', ascending=False)

,col_B,col_A,col_C
2,3,6,9
1,2,5,8
0,1,4,7


In [54]:
data = {'customer': [101, 102, 103, 104, 101], 'cat': ['cat2', 'cat2', 'cat1', 'cat1', 'cat2'],
        'imp': ['yes', 'no', 'yes', 'yes', 'yes'], 
        'sales': [123, 52, 214, 663, 125]}
df = pd.DataFrame(data)
df

,customer,cat,imp,sales
0,101,cat2,yes,123
1,102,cat2,no,52
2,103,cat1,yes,214
3,104,cat1,yes,663
4,101,cat2,yes,125


In [55]:
df.loc[[1,2], ['customer', 'sales']]

,customer,sales
1,102,52
2,103,214


In [56]:
df.groupby(['customer'])['sales'].mean()

customer
101    124.0
102     52.0
103    214.0
104    663.0
Name: sales, dtype: float64

In [57]:
df.drop('imp', axis=1)

,customer,cat,sales
0,101,cat2,123
1,102,cat2,52
2,103,cat1,214
3,104,cat1,663
4,101,cat2,125


In [58]:
df

,customer,cat,imp,sales
0,101,cat2,yes,123
1,102,cat2,no,52
2,103,cat1,yes,214
3,104,cat1,yes,663
4,101,cat2,yes,125
